In [51]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [52]:
dataset = pd.read_csv("MultipleLinearRegressionData.csv")


In [53]:
dataset.head() #명목변수 있음 (place)

hour  absent    place  score
0   0.5       3     Home     10
1   1.2       4  Library      8
2   1.8       2     Cafe     14
3   2.4       0     Cafe     26
4   2.6       2     Home     22

In [54]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [55]:
X, y

(array([[0.5, 3, 'Home'],
        [1.2, 4, 'Library'],
        [1.8, 2, 'Cafe'],
        [2.4, 0, 'Cafe'],
        [2.6, 2, 'Home'],
        [3.2, 0, 'Home'],
        [3.9, 0, 'Library'],
        [4.4, 0, 'Library'],
        [4.5, 5, 'Home'],
        [5.0, 1, 'Cafe'],
        [5.3, 2, 'Cafe'],
        [5.8, 0, 'Cafe'],
        [6.0, 3, 'Library'],
        [6.1, 1, 'Cafe'],
        [6.2, 1, 'Library'],
        [6.9, 4, 'Home'],
        [7.2, 2, 'Cafe'],
        [8.4, 1, 'Home'],
        [8.6, 1, 'Library'],
        [10.0, 0, 'Library']], dtype=object),
 array([ 10,   8,  14,  26,  22,  30,  42,  48,  38,  58,  60,  72,  62,
         68,  72,  58,  76,  86,  90, 100]))

In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop = 'first'), [2])], remainder='passthrough')

In [57]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(drop='first'), [2])])

In [58]:
X_ct = ct.fit_transform(X)
X_ct

array([[1.0, 0.0, 0.5, 3],
       [0.0, 1.0, 1.2, 4],
       [0.0, 0.0, 1.8, 2],
       [0.0, 0.0, 2.4, 0],
       [1.0, 0.0, 2.6, 2],
       [1.0, 0.0, 3.2, 0],
       [0.0, 1.0, 3.9, 0],
       [0.0, 1.0, 4.4, 0],
       [1.0, 0.0, 4.5, 5],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.3, 2],
       [0.0, 0.0, 5.8, 0],
       [0.0, 1.0, 6.0, 3],
       [0.0, 0.0, 6.1, 1],
       [0.0, 1.0, 6.2, 1],
       [1.0, 0.0, 6.9, 4],
       [0.0, 0.0, 7.2, 2],
       [1.0, 0.0, 8.4, 1],
       [0.0, 1.0, 8.6, 1],
       [0.0, 1.0, 10.0, 0]], dtype=object)

In [59]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(
    X_ct, y, test_size = 0.2, random_state = 0
)

In [60]:
X_test,  y_test

(array([[0.0, 1.0, 8.6, 1],
        [0.0, 1.0, 1.2, 4],
        [0.0, 1.0, 10.0, 0],
        [1.0, 0.0, 4.5, 5]], dtype=object),
 array([ 90,   8, 100,  38]))

In [61]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
lr = LinearRegression()
sr = SGDRegressor()

In [62]:
lr.fit(X_train, y_train)

LinearRegression()

In [63]:
sr.fit(X_train, y_train)

SGDRegressor()

In [64]:
lr.coef_, sr.coef_

(array([-5.82712824, -1.04450647, 10.40419528, -1.64200104]),
 array([-2.20459018,  0.63170003, 10.68748383, -1.83046102]))

In [65]:
lr.score(X_test, y_test), lr.score(X_train, y_train)

(0.9859956178877447, 0.9623352565265527)

In [66]:
sr.score(X_test, y_test), sr.score(X_train, y_train)

(0.9821301144795574, 0.9570061600640076)

In [67]:
lr.predict(X_test)

array([ 92.15457859,  10.23753043, 108.36245302,  38.14675204])

In [68]:
sr.predict(X_test)

array([ 92.83632081,   8.25755743, 109.62925919,  38.85950283])