In [ ]:
print("hello python")

hello python


In [ ]:
import numpy as np
import pandas as pd

x = np.pi
print(x)

3.141592653589793


lst = [1,2,3,4,5,6]
type(lst)

lst2 = (1,2,3,4,5,6)
type(lst2)

lst3 = {a:[1,2,3,4,5],b:[a, b, c, d, e]}
type(lst3)

In [ ]:
lst = [1,2,3,4,5,6]
type(lst)

lst2 = (1,2,3,4,5,6)
type(lst2)

lst3 = {'A':[1,2,3,4,5], 'B':['a', 'b', 'c', 'd', 'e']}
type(lst3)

lst * 3

dict

In [16]:
lst * 3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [17]:
lst + lst

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
data1 = (7, 7.5, 8, 9)
arr = np.array(data1)
arr



In [22]:
arr1 = arr.tolist()
arr1

[7.0, 7.5, 8.0, 9.0]

In [24]:
arr * arr


array([49.  , 56.25, 64.  , 81.  ])

In [ ]:
tod = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
tod arr.2d[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr4 = np.random.randn(4, 5)
arr4

array([[-0.34083505, -0.17997737,  0.34834564,  0.33247955, -0.16098892],
       [-0.3066769 , -0.25549164, -0.88205048, -0.94716747, -0.02903142],
       [-1.1972421 ,  0.51793597,  1.5589822 ,  1.4265816 , -0.04016023],
       [-0.15047826,  0.92646779, -0.38274704,  1.34594859, -0.65205258]])

In [30]:
arr4.mean()

np.float64(0.04659209401823999)

In [31]:
arr.sum(), arr.min(), arr.max() 
arr.sum(axis=1) , arr.sum(axis=0)

(array([ 0.7286554 , -0.08548136, -0.61140921, -0.1962507 ]),
 array([ 1.10468813, -1.90276672, -0.39742953, -1.50790993,  2.53893219]))

In [32]:
arr.sum(axis=1) , arr.sum(axis=0)

(array([ 0.7286554 , -0.08548136, -0.61140921, -0.1962507 ]),
 array([ 1.10468813, -1.90276672, -0.39742953, -1.50790993,  2.53893219]))